---
- name: Install prerequisites
  become: true
  apt:
    update_cache: yes
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Add Docker GPG key
  become: true
  shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Add Docker APT repo
  become: true
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch={{ docker_arch | default('amd64') }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_facts.lsb.codename }} stable
    mode: "0644"

- name: apt update
  become: true
  apt:
    update_cache: yes

- name: Install Docker Engine + Compose v2
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Enable & start Docker
  become: true
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add ubuntu user to docker group
  become: true
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Ensure compose dir exists
  become: true
  file:
    path: /opt/apps
    state: directory
    mode: "0755"

- name: Drop Gatus config
  become: true
  copy:
    dest: /opt/apps/config.yaml
    mode: "0644"
    content: |
      endpoints:
        - name: nginx-on-80
          url: http://localhost:80/
          interval: 30s
          conditions:
            - "[STATUS] == 200"

- name: Drop docker-compose (nginx + gatus)
  become: true
  copy:
    dest: /opt/apps/docker-compose.yml
    mode: "0644"
    content: |
      services:
        nginx:
          image: nginx:latest
          restart: unless-stopped
          ports:
            - "80:80"
        gatus:
          image: twinproduction/gatus:latest
          restart: unless-stopped
          volumes:
            - /opt/apps/config.yaml:/config/config.yaml:ro
          ports:
            - "8080:8080"

- name: Bring up stack
  become: true
  community.docker.docker_compose_v2:
    project_src: /opt/apps
    state: present
