name: Provision VM (Ansible)
on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
    paths: [ "ansible/**", ".github/workflows/provision.yml" ]

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible + collection
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core
          ansible-galaxy collection install community.docker

      - name: Write SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_vm
          chmod 600 ~/.ssh/id_vm

      - name: Create inventory
        run: |
          mkdir -p ansible/inventory
          printf "[web]\n%s ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_vm\n" "${{ secrets.VM_HOST }}" > ansible/inventory/hosts.ini

      - name: Run playbook
        working-directory: ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: ansible-playbook site.yml
